name: Publish to FlakeHub

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+*"

permissions:
  contents: read
  id-token: write

jobs:
  publish:
    runs-on: ubuntu-24.04
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - uses: DeterminateSystems/determinate-nix-action@527f17dd63d2d60d3e5552934bc84b9a33a14d11 # v3

      - run: nix flake check --no-build --all-systems --no-update-lock-file
      - run: nix flake check -L --no-update-lock-file

      - uses: DeterminateSystems/flakehub-push@abcff4fb351e63f852f5fb2b9af0ae4e69de07d4
        with:
          visibility: public
          tag: ${{ github.ref_name }}
          spdx-expression: MIT
          error-on-conflict: true
